CREATE DATABASE SPORTS;

USE SPORTS;

CREATE TABLE IF NOT EXISTS SPORTS(id int,sports_name varchar(20),no_of_players int,mode_of_game enum('INDOOR','OUTDOOR'));

SELECT * FROM SPORTS;

INSERT INTO SPORTS values(1,'CRICKET',11,'OUTDOOR');
INSERT INTO SPORTS values(2,'CHESS',2,'INDOOR');
INSERT INTO SPORTS values(3,'BATMITON',4,'OUTDOOR');


